### ISSUE TITLE
99- Comments on GAM

### ISSUE THREAD

**Issue by VLucet** [pedersen-fisheries-lab/sspm#113]

**Comment by VLucet** [comment]
I quote from #54 :
> Add "()" after "spm_smooth" because it is a function name. 
This has been dealt with.

This remains:
> "spatiotemporal" here is a bit misleading because you are just running discrete GAMS per group not linking the GAMs based on physical proximity like a full on spatial model would do, i.e., there are no Gaussian random fields that associate one point in space to the physical location of near and far points.

**Comment by VLucet** [comment]
@eric-pedersen I would like your input on how to address this specific comment

**Comment by eric-pedersen** [comment]
Just double-checking: this refers to line 77, correct? We could change it to:

"Using GAMs to calculate spatially smoothed yearly estimates of biomass and environmental predictors for each patch from trawl-level data"

The comment's correct that there is no information shared across years except the penalty term itself, so I think this wording is a bit clearer.

**Comment by VLucet** [comment]
it was for line 99:

> The spm_smooth function use spatiotemporal GAM models to smooth the biomass and
predictor data, based on the spatial structure from sspm_discrete_boundary. The user
specifies a GAM formula with custom smooth terms. The output is another sspm_dataset
object with a smoothed_data slot which contains the smoothed predictions for all patches.

but given your input  I can reframe:

> 	4. The `spm_smooth()` uses GAMs to calculate spatially smoothed yearly estimates of biomass and environmental predictors for each patch from trawl-level data, based on the spatial structure from the `sspm_discrete_boundary` object. The user specifies a GAM formula with custom smooth terms. The output is another `sspm_dataset` object with a `smoothed_data` slot which contains the smoothed predictions for all patches.
