### ISSUE TITLE
Crowder et al. is not a book

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pedersen-fisheries-lab/sspm#142]
I am not sure why you embrace every word in the title of Crowder et al. because it is not a book. Shouldn't you just let the csl file deal with how it wants the title to be capitalized rather than forcing each word to be upper cased?

https://github.com/pedersen-fisheries-lab/sspm/blob/72993d4bc6319e198335624d2057ad966d70e1c9/paper/paper.bib#L208

This issue is part of a review for JOSS, see https://github.com/openjournals/joss-reviews/issues/4724.

**Comment by VLucet** [comment]
This is not voluntary. Zotero extracts the bib info from he Annual reviews website and exports it as such, because paper titles tend to be capitalized. I can change it.

**Comment by kellijohnson-NOAA** [comment]
Ahh thanks for the information regarding your process ... it is often the case that publishers use incorrect LaTeX or formatting rules in their citation information. Another typo I found was with prager_suite_1994 where the journal should just be "Fishery Bulletin" with the NOAA stuff. I actually work for NOAA, which is why I noticed it.

**Comment by VLucet** [comment]
For sure, ill fix that too. Same thing there, Zotero generated the name.
