### ISSUE TITLE
Copyright holder

### ISSUE THREAD

**Issue by VLucet** [pedersen-fisheries-lab/sspm#44]
See here: https://r-pkgs.org/license.html#copyright-holder
@eric-pedersen Who is cph holder for this package? I've put you for now but let me know if there is something I'm missing.

**Comment by eric-pedersen** [comment]
Given the contribution you have made to this project, and the lead in developing the code, you should hold copyright to this. The University intellectual property policy states that any member (including yourself) retains copyright except for works directly commissioned by the university (or by a third party as part of a contact): https://www.concordia.ca/content/dam/common/docs/policies/official-policies/VPRGS-9.pdf
