### ISSUE TITLE
More freedom for plotting

### ISSUE THREAD

**Issue by firvine** [pedersen-fisheries-lab/sspm#46]
This package is great, but:
- [x] I would like to modify mapping aesthetics such as the size of points and lines
- [x] I would also like control plotting the predicted or smoothed variables. For example, only plotting the predicted curve and not the smoothed one.
- [x] I would also love to add CIs to the smoothed data.
- [x] Is it possible to create an object with the fit values and CIs?

**Comment by VLucet** [comment]
In separate branch, ive made it easier to plot only predictions

**Comment by VLucet** [comment]
CIs added as well, but the plotting may not be achieved given aggregation style cannot always be inferred
